/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.1.41 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `ww_menu` (
	`menu_item_id` int ,
	`parent_menu_item_id` int ,
	`sequence` tinyint ,
	`label` varchar ,
	`icon` varchar ,
	`description` text (196605),
	`menu_item_type_id` int ,
	`mod_id` int ,
	`uri` text (196605),
	`method` text (196605),
	`created_on` timestamp ,
	`created_by` int ,
	`modified_on` datetime ,
	`modified_by` int ,
	`can_delete` tinyint ,
	`deleted` tinyint 
); 
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('1','0','1','Dashboard','fa-home',NULL,'1','9',NULL,NULL,'2013-11-08 05:58:49','1','2014-04-11 13:56:43','1','0','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('2','0','2','My Record','fa-user',NULL,'3','0',NULL,NULL,'2014-02-06 05:03:45','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('3','0','3','Employee','fa-folder-open-o',NULL,'3','0',NULL,NULL,'2014-02-06 05:03:52','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('4','0','4','Appraisal','fa-trophy',NULL,'3','0',NULL,NULL,'2014-02-06 05:04:05','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('5','0','4','Timekeeping','fa-clock-o','','3','1','','','2014-02-06 05:04:26','0','2014-07-02 07:05:20','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('6','0','8','Recruitment','fa-search-plus','','3','122','','','2014-02-06 05:04:34','0','2015-08-26 11:56:55','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('7','0','7','Training','fa-group',NULL,'3','0',NULL,NULL,'2014-02-06 05:04:40','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('8','0','10','Reports','fa-bar-chart-o',NULL,'3','0',NULL,NULL,'2014-02-06 05:09:05','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('9','0','9','Master','fa-th',NULL,'3','0',NULL,NULL,'2013-11-12 07:48:06','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('10','0','11','System Configuration','fa-cogs',NULL,'1','5',NULL,NULL,'2014-02-06 05:25:19','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('11','0','11','Reserved 1','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 05:25:29','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('12','0','12','Reserved 2','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:15:28','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('13','10','1','Settings','fa-list',NULL,'1','5',NULL,NULL,'2013-11-12 07:54:12','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('14','10','2','Module Manager','fa-user',NULL,'1','1',NULL,NULL,'2013-11-13 08:09:21','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('15','10','3','Menu Manager','fa-list',NULL,'1','7',NULL,NULL,'2013-11-22 03:09:20','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('16','10','4','Template Manager','fa-list',NULL,'3','0',NULL,NULL,'2014-02-05 12:42:41','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('17','10','5','Utilities','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 05:14:13','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('18','10','4','Roles','fa-list',NULL,'1','4',NULL,NULL,'2014-02-06 05:27:08','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('19','10','5','Permission','fa-list',NULL,'1','3',NULL,NULL,'2014-02-06 05:27:28','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('20','9','2','Employee Approver','fa-list',NULL,'1','30',NULL,NULL,'2014-02-06 05:27:50','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('21','10','9','Reserved-Setting 4','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 05:28:16','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('22','10','10','Reserved-Setting 5','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 05:28:36','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('23','2','2','201','fa-list','','1','38','','','2014-02-06 06:33:09','0','2014-10-22 16:19:06','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('24','2','1','Schedule','fa-list',NULL,'1','28',NULL,NULL,'2014-02-06 06:33:19','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('25','2','4','Inbox','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:33:40','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('26','2','4','Reserved-My Account 1','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:34:20','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('27','2','5','Reserved-My Account 2','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:34:26','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('28','2','6','Reserved-My Account 3','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:34:32','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('29','2','7','Reserved-My Account 4','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:34:36','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('30','2','8','Reserved-My Account 5','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 06:34:42','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('31','3','1','Employee List','fa-list','','1','43','','','2014-02-06 08:02:24','0','2014-04-16 19:05:42','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('32','3','4','Update 201 Manage','fa-list','','1','70','','','2014-02-06 08:03:02','0','2014-06-19 13:22:18','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('33','3','8','Clearance','','','1','134','','','2014-02-06 08:03:44','0','2016-01-05 12:01:32','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('34','3','2','Subordinates','fa-list','','1','45','','','2014-02-06 08:05:22','0','2014-04-23 14:11:10','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('35','3','3','Birthdays','fa-list',NULL,'1','41',NULL,NULL,'2014-02-06 08:05:27','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('36','3','6','Reserved-Employee 3','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:05:30','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('37','3','7','Reserved-Employee 4','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:05:34','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('38','3','8','Reserved-Employee 5','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:05:40','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('39','3','9','Reserved-Employee 6','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:05:44','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('40','3','10','Reserved-Employee 7','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:05:47','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('41','3','11','Reserved-Employee 8','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:06:00','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('42','3','12','Reserved-Employee 9','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:07:41','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('43','3','13','Reserved-Employee 10','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:07:52','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('44','5','9','Work Schedule','fa-list',NULL,'1','27',NULL,NULL,'2014-02-06 08:08:10','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('45','5','6','Daily Time Records','fa-list',NULL,'1','31',NULL,NULL,'2014-02-06 08:08:30','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('46','5','1','Application','fa-list',NULL,'1','42',NULL,NULL,'2014-02-06 08:08:58','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('47','5','11','DTR Period','fa-list',NULL,'1','29',NULL,NULL,'2014-02-06 08:09:48','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('48','5','12','DTR Uploading','fa-list','','1','46','','','2014-02-06 08:10:34','0','2016-06-27 17:32:27','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('49','5','2','Application - Manage','fa-list','','1','44','','','2014-02-06 08:11:04','0','2014-07-21 20:06:43','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('50','5','7','Reserved-Time Record 2','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:11:07','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('51','5','8','Reserved-Time Record 3','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:11:10','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('52','5','9','Reserved-Time Record 4','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:11:13','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('53','5','10','Reserved-Time Record 5','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:11:17','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('54','6','1','Manpower Planning','fa-list','','1','120','','','2014-02-06 08:28:38','0','2016-01-12 09:48:48','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('55','6','2','Manpower Request','Personnel Requisition','','1','122','','','2014-02-06 08:28:50','0','2016-01-12 09:49:31','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('56','6','3','Applicant Monitoring','fa-list','','1','125','','','2014-02-06 08:29:25','0','2015-08-26 12:04:51','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('57','6','4','Applicant List','fa-list','','1','121','','','2014-02-06 08:30:30','0','2015-08-26 12:04:23','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('58','6','5','Applicant Registration (External)','fa-list','','1','124','','','2014-02-06 08:30:51','0','2015-08-26 12:05:55','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('59','6','6','Reserved-Personnel 1','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:31:09','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('60','6','7','Reserved-Personnel 2','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:31:15','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('61','6','8','Reserved-Personnel 3','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:31:18','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('62','6','9','Reserved-Personnel 4','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:31:22','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('63','6','10','Reserved-Personnel 5','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:31:25','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('64','9','1','Employee Master','fa-list',NULL,'1','23',NULL,NULL,'2014-02-06 08:32:56','0',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('65','9','3','Employee Master 2','fa-list','','1','219','','','2014-02-06 08:33:05','0','2015-12-14 17:05:27','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('66','9','6','Appraisal Master','fa-list','','1','113','','','2014-02-06 08:33:18','0','2015-01-22 13:48:03','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('67','9','4','Time Keeping Master','fa-list','','1','78','','','2014-02-06 08:33:34','0','2014-08-03 09:08:18','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('68','9','9','Personnel Manager','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:33:56','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('69','9','7','Training Manager','fa-list','','1','198','','','2014-02-06 08:34:24','0','2017-02-02 14:44:55','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('70','9','11','Analytics References','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:34:30','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('71','9','8','Reserved-Admin 1','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:34:48','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('72','9','9','Reserved-Admin 2','fa-list',NULL,'3','0',NULL,NULL,'2014-02-06 08:35:29','0',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('73','9','5','Payroll Master','fa-money','','1','9','admin/payroll/settings','payroll','2014-05-06 06:41:02','1','2014-05-05 18:01:33','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('74','0','5','Payroll','fa-money','','1','9','payroll/setup','payroll_setup','2014-05-13 02:33:41','1','2014-05-12 11:35:04','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('75','3','5','Announcement','','','1','73','','','2014-06-21 10:21:37','1','2014-06-20 13:25:05','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('76','5','3','Application - Admin','fa-list','','1','74','','','2014-06-25 05:16:18','1','2014-07-21 20:01:55','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('77','9','4','Form Policy','','','1','72','','','2014-06-26 02:36:08','1',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('78','2','5','Update 201','fa-folder','','1','75','','','2014-06-28 04:33:03','1','2014-06-27 13:36:21','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('79','5','8','Time Records - Admin','','','1','58','','','2014-07-09 06:40:17','1','2014-07-21 19:58:28','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('80','5','7','Time Records - Manage','','','1','77','','','2014-07-09 07:00:30','1','2014-07-21 20:06:17','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('81','74','1','Chart of Accounts','','','1','54','','','2014-07-23 05:32:26','1','2014-07-22 14:37:23','1','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('82','10','6','Utilities','','','1','9','','utilities','2014-07-31 04:26:17','1',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('83','5','5','Leave Balance - Admin','','','1','85','','','2014-08-01 04:39:11','1','2014-08-04 14:48:18','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('84','5','4','Leave Balance','','','1','86','','','2014-08-02 00:49:40','1','2014-08-01 09:50:56','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('86','3','6','Movement','fa-user','','1','87','','','2014-08-20 06:55:14','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('87','9','9','Report Generator','','','1','88','','','2014-09-11 02:35:47','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('88','5','10','DTR Summary','','','1','89','','','2014-09-19 02:20:52','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('89','8','1','Generate Reports','','','1','9','','reports','2014-09-23 05:38:28','1','2014-09-22 15:36:59','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('93','8','2','Demographics','','','1','126','','','2015-01-08 10:32:51','1','2015-01-09 15:21:48','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('94','8','3','Company Demographics','','','1','126','','company','2015-01-14 06:18:21','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('95','2','3','Payroll','','','1','170','','','2015-03-19 04:43:00','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('96','0','7','Appraisal','fa fa-trophy','','3','1','','','2015-01-22 06:05:08','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('97','96','3','Appraisal','','','1','116','','','2015-01-22 06:06:40','1','2015-01-26 15:24:52','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('98','96','1','Target Setting','','','1','109','','','2015-01-22 06:09:33','1','2015-06-15 18:24:42','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('99','96','2','Target Setting Period','','','1','107','','','2015-01-22 06:10:51','1','2015-06-15 18:25:00','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('102','96','5','Appraisal Period','','','1','111','','','2015-01-22 06:13:57','1','2015-01-26 15:21:09','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('103','96','4','Appraisal Manage','','','1','112','','','2015-01-22 06:14:44','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('106','3','7','Code of Conduct','','','1','138','','','2015-01-24 05:33:34','1','2015-02-03 16:02:39','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('107','3','10','Resources','','','1','143','','','2015-01-29 00:40:57','1','2015-09-02 17:56:17','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('108','9','8','Clearance Signatory','','','1','163','','','2015-02-11 03:41:39','1','2017-01-26 09:34:23','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('111','3','6','Memo Manage','','','1','166','','','2015-02-12 00:59:52','1',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('114','120','1','Outgoing Emails','','','1','178','','','2015-05-05 00:38:49','1','2017-01-26 09:38:12','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('115','6','6','Applicant Registration (Internal)','','','1','129','','','2015-08-27 03:06:31','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('116','3','9','Clearance Manage','','','3','164','partner/clearance_manage','','2016-01-08 08:29:57','1','2016-01-07 16:32:04','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('117','3','1','Health Information','','','1','130','','','2016-02-20 00:16:00','1',NULL,'0','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('118','10','1','Test Menu one','','','2','5','','','2016-07-20 04:55:36','1','2016-07-19 13:56:35','1','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('119','9','1','ab','ab','ab','1','54','ab','ab','2016-07-23 10:08:52','1','2016-07-22 19:09:17','1','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('120','0','12','Utilities','fa-cogs','','1','5','','','2017-01-26 01:36:08','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('121','0','6','Training','fa-folder-open-o','','3','54','','','2017-02-01 07:09:26','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('122','121','1','Employee Training Database','','','1','241','','','2017-02-01 07:16:16','1','2017-02-01 15:16:46','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('123','121','1','Training Calendar','','','1','242','','','2017-02-01 09:39:20','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('124','121','1','Level 2 and 3 Training Evaluation','','','1','243','','','2017-02-02 05:39:38','1','2017-02-02 15:40:47','1','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('125','121','1','Training Evaluation','','','1','244','','','2017-02-02 05:50:23','1',NULL,'0','1','0');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('126','9','1','Branch','','','1','251','','','2017-03-04 07:22:28','1','2017-03-05 11:14:58','1','1','1');
insert into `ww_menu` (`menu_item_id`, `parent_menu_item_id`, `sequence`, `label`, `icon`, `description`, `menu_item_type_id`, `mod_id`, `uri`, `method`, `created_on`, `created_by`, `modified_on`, `modified_by`, `can_delete`, `deleted`) values('127','120','1','Scheduler','','','1','252','','','2017-03-15 11:45:37','1',NULL,'0','1','0');
